import type { Item, Vendor, Review, PriceHistory, Franchise, Category } from '@/types';

export const mockFranchises: Franchise[] = [
  { id: '1', name: 'Pokemon', slug: 'pokemon', logo_url: null, banner_url: null, sort_order: 1, created_at: new Date().toISOString() },
  { id: '2', name: 'One Piece', slug: 'one-piece', logo_url: null, banner_url: null, sort_order: 2, created_at: new Date().toISOString() },
  { id: '3', name: 'Sports Cards', slug: 'sports-cards', logo_url: null, banner_url: null, sort_order: 3, created_at: new Date().toISOString() },
  { id: '4', name: 'Funko Pop', slug: 'funko', logo_url: null, banner_url: null, sort_order: 4, created_at: new Date().toISOString() },
  { id: '5', name: 'Gundam', slug: 'gundam', logo_url: null, banner_url: null, sort_order: 5, created_at: new Date().toISOString() },
  { id: '6', name: 'Marvel', slug: 'marvel', logo_url: null, banner_url: null, sort_order: 6, created_at: new Date().toISOString() },
  { id: '7', name: 'Dragon Ball', slug: 'dragon-ball', logo_url: null, banner_url: null, sort_order: 7, created_at: new Date().toISOString() },
  { id: '8', name: 'MTG', slug: 'mtg', logo_url: null, banner_url: null, sort_order: 9, created_at: new Date().toISOString() },
];

export const mockCategories: Category[] = [
  { id: '1', name: 'Trading Cards', slug: 'trading-cards', parent_id: null, icon_url: null, sort_order: 1, created_at: new Date().toISOString() },
  { id: '2', name: 'Graded Cards', slug: 'graded-cards', parent_id: null, icon_url: null, sort_order: 2, created_at: new Date().toISOString() },
  { id: '3', name: 'Sealed Products', slug: 'sealed-products', parent_id: null, icon_url: null, sort_order: 3, created_at: new Date().toISOString() },
  { id: '4', name: 'Figures', slug: 'figures', parent_id: null, icon_url: null, sort_order: 4, created_at: new Date().toISOString() },
  { id: '5', name: 'Watches', slug: 'watches', parent_id: null, icon_url: null, sort_order: 5, created_at: new Date().toISOString() },
  { id: '6', name: 'Comics & Manga', slug: 'comics', parent_id: null, icon_url: null, sort_order: 6, created_at: new Date().toISOString() },
  { id: '7', name: 'Memorabilia', slug: 'memorabilia', parent_id: null, icon_url: null, sort_order: 7, created_at: new Date().toISOString() },
];

const mockVendor: Vendor = {
  id: 'v1',
  user_id: 'u1',
  shop_name: 'CardMaster Dubai',
  slug: 'cardmaster-dubai',
  description: 'Premium TCG cards from the heart of Dubai. Specializing in Pokemon and One Piece.',
  logo_url: null,
  banner_url: null,
  status: 'active',
  tier: 'gold',
  rating_avg: 4.8,
  rating_count: 156,
  total_sales: 342,
  response_rate: 98.5,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const mockVendor2: Vendor = {
  id: 'v2',
  user_id: 'u2',
  shop_name: 'Rarity Vault',
  slug: 'rarity-vault',
  description: 'Your source for rare and graded collectibles.',
  logo_url: null,
  banner_url: null,
  status: 'active',
  tier: 'diamond',
  rating_avg: 4.95,
  rating_count: 520,
  total_sales: 1203,
  response_rate: 99.2,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockVendors: Vendor[] = [mockVendor, mockVendor2];

export const mockItems: Item[] = [
  {
    id: 'item1',
    vendor_id: 'v1',
    category_id: '2',
    franchise_id: '1',
    title: 'Charizard VMAX Rainbow Rare - PSA 10',
    slug: 'charizard-vmax-rainbow-psa10',
    description: 'Perfect condition Charizard VMAX Rainbow Rare from Darkness Ablaze. PSA 10 Gem Mint grade. One of the most sought-after modern Pokemon cards.',
    price: 450,
    compare_price: 520,
    currency: 'USD',
    condition: 'NM',
    year: 2020,
    rarity: 'Secret Rare',
    edition: '1st Edition',
    set_name: 'Darkness Ablaze',
    card_number: '074/073',
    language: 'EN',
    is_graded: true,
    grade_company: 'PSA',
    grade_score: 10,
    grade_cert_no: '12345678',
    status: 'active',
    stock: 1,
    is_featured: true,
    is_sale: true,
    sale_price: 399,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    vendor: mockVendor,
    images: [
      { id: 'img1', item_id: 'item1', url: '/placeholder-card.svg', alt_text: 'Charizard VMAX', sort_order: 0, is_primary: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'item2',
    vendor_id: 'v1',
    category_id: '1',
    franchise_id: '1',
    title: 'Pikachu VMAX - Vivid Voltage',
    slug: 'pikachu-vmax-vivid',
    description: 'Beautiful Pikachu VMAX from Vivid Voltage set.',
    price: 85,
    compare_price: null,
    currency: 'USD',
    condition: 'NM',
    year: 2020,
    rarity: 'Ultra Rare',
    edition: null,
    set_name: 'Vivid Voltage',
    card_number: '044/185',
    language: 'EN',
    is_graded: false,
    grade_company: null,
    grade_score: null,
    grade_cert_no: null,
    status: 'active',
    stock: 3,
    is_featured: false,
    is_sale: false,
    sale_price: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    vendor: mockVendor,
    images: [
      { id: 'img2', item_id: 'item2', url: '/placeholder-card.svg', alt_text: 'Pikachu VMAX', sort_order: 0, is_primary: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'item3',
    vendor_id: 'v2',
    category_id: '1',
    franchise_id: '2',
    title: 'Luffy Gear 5 - Paramount War OP02',
    slug: 'luffy-gear5-op02',
    description: 'Monkey D. Luffy Gear 5 leader card from One Piece Card Game.',
    price: 120,
    compare_price: 150,
    currency: 'USD',
    condition: 'NM',
    year: 2023,
    rarity: 'Leader',
    edition: null,
    set_name: 'Paramount War OP02',
    card_number: 'OP02-062',
    language: 'EN',
    is_graded: false,
    grade_company: null,
    grade_score: null,
    grade_cert_no: null,
    status: 'active',
    stock: 2,
    is_featured: true,
    is_sale: false,
    sale_price: null,
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 172800000).toISOString(),
    vendor: mockVendor2,
    images: [
      { id: 'img3', item_id: 'item3', url: '/placeholder-card.svg', alt_text: 'Luffy Gear 5', sort_order: 0, is_primary: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'item4',
    vendor_id: 'v2',
    category_id: '2',
    franchise_id: '3',
    title: 'Luka Doncic Prizm Silver - BGS 9.5',
    slug: 'luka-doncic-prizm-bgs95',
    description: 'Luka Doncic 2018-19 Panini Prizm Silver Rookie Card. BGS 9.5 Gem Mint.',
    price: 1200,
    compare_price: null,
    currency: 'USD',
    condition: 'NM',
    year: 2018,
    rarity: 'Rookie',
    edition: null,
    set_name: 'Prizm',
    card_number: '280',
    language: 'EN',
    is_graded: true,
    grade_company: 'BGS',
    grade_score: 9.5,
    grade_cert_no: '87654321',
    status: 'active',
    stock: 1,
    is_featured: true,
    is_sale: false,
    sale_price: null,
    created_at: new Date(Date.now() - 259200000).toISOString(),
    updated_at: new Date(Date.now() - 259200000).toISOString(),
    vendor: mockVendor2,
    images: [
      { id: 'img4', item_id: 'item4', url: '/placeholder-card.svg', alt_text: 'Luka Doncic Prizm', sort_order: 0, is_primary: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'item5',
    vendor_id: 'v1',
    category_id: '4',
    franchise_id: '6',
    title: 'Spider-Man (Miles Morales) Funko Pop #402',
    slug: 'spiderman-miles-funko-402',
    description: 'Spider-Man Miles Morales Funko Pop vinyl figure. Exclusive edition.',
    price: 35,
    compare_price: 45,
    currency: 'USD',
    condition: 'NM',
    year: 2023,
    rarity: 'Exclusive',
    edition: 'Limited',
    set_name: 'Marvel',
    card_number: null,
    language: 'EN',
    is_graded: false,
    grade_company: null,
    grade_score: null,
    grade_cert_no: null,
    status: 'active',
    stock: 5,
    is_featured: false,
    is_sale: true,
    sale_price: 28,
    created_at: new Date(Date.now() - 345600000).toISOString(),
    updated_at: new Date(Date.now() - 345600000).toISOString(),
    vendor: mockVendor,
    images: [
      { id: 'img5', item_id: 'item5', url: '/placeholder-card.svg', alt_text: 'Spider-Man Funko', sort_order: 0, is_primary: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'item6',
    vendor_id: 'v2',
    category_id: '3',
    franchise_id: '1',
    title: 'Pokemon 151 Booster Box (Japanese)',
    slug: 'pokemon-151-booster-box-jp',
    description: 'Sealed Pokemon Card 151 Booster Box. Japanese version. 20 packs.',
    price: 95,
    compare_price: null,
    currency: 'USD',
    condition: 'NM',
    year: 2023,
    rarity: null,
    edition: null,
    set_name: 'Pokemon Card 151',
    card_number: null,
    language: 'JP',
    is_graded: false,
    grade_company: null,
    grade_score: null,
    grade_cert_no: null,
    status: 'active',
    stock: 8,
    is_featured: true,
    is_sale: false,
    sale_price: null,
    created_at: new Date(Date.now() - 432000000).toISOString(),
    updated_at: new Date(Date.now() - 432000000).toISOString(),
    vendor: mockVendor2,
    images: [
      { id: 'img6', item_id: 'item6', url: '/placeholder-card.svg', alt_text: 'Pokemon 151 Box', sort_order: 0, is_primary: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'item7',
    vendor_id: 'v1',
    category_id: '1',
    franchise_id: '7',
    title: 'Son Goku Ultra Instinct SCR',
    slug: 'goku-ultra-instinct-scr',
    description: 'Dragon Ball Super Card Game Son Goku Ultra Instinct Secret Rare.',
    price: 180,
    compare_price: 220,
    currency: 'USD',
    condition: 'LP',
    year: 2022,
    rarity: 'SCR',
    edition: null,
    set_name: 'Realm of the Gods',
    card_number: 'BT16-SCR01',
    language: 'EN',
    is_graded: false,
    grade_company: null,
    grade_score: null,
    grade_cert_no: null,
    status: 'active',
    stock: 1,
    is_featured: false,
    is_sale: true,
    sale_price: 159,
    created_at: new Date(Date.now() - 518400000).toISOString(),
    updated_at: new Date(Date.now() - 518400000).toISOString(),
    vendor: mockVendor,
    images: [
      { id: 'img7', item_id: 'item7', url: '/placeholder-card.svg', alt_text: 'Goku Ultra Instinct', sort_order: 0, is_primary: true, created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'item8',
    vendor_id: 'v2',
    category_id: '1',
    franchise_id: '8',
    title: 'Black Lotus (Unlimited) - MTG',
    slug: 'black-lotus-unlimited',
    description: 'Magic: The Gathering Black Lotus from Unlimited Edition. A piece of TCG history.',
    price: 25000,
    compare_price: null,
    currency: 'USD',
    condition: 'MP',
    year: 1993,
    rarity: 'Power Nine',
    edition: 'Unlimited',
    set_name: 'Alpha/Beta/Unlimited',
    card_number: null,
    language: 'EN',
    is_graded: false,
    grade_company: null,
    grade_score: null,
    grade_cert_no: null,
    status: 'active',
    stock: 1,
    is_featured: true,
    is_sale: false,
    sale_price: null,
    created_at: new Date(Date.now() - 604800000).toISOString(),
    updated_at: new Date(Date.now() - 604800000).toISOString(),
    vendor: mockVendor2,
    images: [
      { id: 'img8', item_id: 'item8', url: '/placeholder-card.svg', alt_text: 'Black Lotus', sort_order: 0, is_primary: true, created_at: new Date().toISOString() },
    ],
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r1', user_id: 'u3', item_id: 'item1', vendor_id: 'v1', order_id: 'o1',
    rating: 5, title: 'Perfect card!', content: 'Exactly as described. PSA 10 slab in perfect condition. Fast shipping too!',
    images: null, is_verified: true, created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    user: { id: 'u3', email: 'collector@email.com', name: 'Ahmed K.', avatar_url: null, phone: null, role: 'buyer', created_at: '', updated_at: '' },
  },
  {
    id: 'r2', user_id: 'u4', item_id: 'item1', vendor_id: 'v1', order_id: 'o2',
    rating: 4, title: 'Great seller', content: 'Card is amazing. Shipping took a bit longer than expected but overall great experience.',
    images: null, is_verified: true, created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    user: { id: 'u4', email: 'buyer2@email.com', name: 'Sarah M.', avatar_url: null, phone: null, role: 'buyer', created_at: '', updated_at: '' },
  },
  {
    id: 'r3', user_id: 'u5', item_id: 'item3', vendor_id: 'v2', order_id: 'o3',
    rating: 5, title: 'Incredible card!', content: 'The Luffy Gear 5 card is even more beautiful in person. Top notch packaging.',
    images: null, is_verified: true, created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    user: { id: 'u5', email: 'op_fan@email.com', name: 'Omar R.', avatar_url: null, phone: null, role: 'buyer', created_at: '', updated_at: '' },
  },
];

export function generatePriceHistory(basePrice: number, days: number): PriceHistory[] {
  const history: PriceHistory[] = [];
  let price = basePrice * 0.85;
  for (let i = days; i >= 0; i--) {
    const change = (Math.random() - 0.45) * (basePrice * 0.03);
    price = Math.max(basePrice * 0.5, Math.min(basePrice * 1.5, price + change));
    history.push({
      id: `ph-${i}`,
      item_id: 'item1',
      card_key: null,
      price: Math.round(price * 100) / 100,
      source: 'raribox',
      recorded_at: new Date(Date.now() - 86400000 * i).toISOString(),
    });
  }
  return history;
}
